<?php
/**
 * Generated by "Autoload generator"
 * @link http://github.com/dmkuznetsov/php-autoloader
 * @date 2013-10-26 22:34
 */
function __dm_autoload_325( $name )
{
	$map = array (
  'Yandex\\Fotki\\Api' => 'source/Yandex/Fotki/Api.php',
  'Yandex\\Fotki\\ApiAbstract' => 'source/Yandex/Fotki/ApiAbstract.php',
  'Yandex\\Fotki\\Api\\AbstractCollection' => 'source/Yandex/Fotki/Api/AbstractCollection.php',
  'Yandex\\Fotki\\Api\\Album' => 'source/Yandex/Fotki/Api/Album.php',
  'Yandex\\Fotki\\Api\\AlbumsCollection' => 'source/Yandex/Fotki/Api/AlbumsCollection.php',
  'Yandex\\Fotki\\Api\\Auth' => 'source/Yandex/Fotki/Api/Auth.php',
  'Yandex\\Fotki\\Api\\Photo' => 'source/Yandex/Fotki/Api/Photo.php',
  'Yandex\\Fotki\\Api\\PhotosCollection' => 'source/Yandex/Fotki/Api/PhotosCollection.php',
  'Yandex\\Fotki\\Api\\ServiceDocument' => 'source/Yandex/Fotki/Api/ServiceDocument.php',
  'Yandex\\Fotki\\Encrypt' => 'source/Yandex/Fotki/Encrypt.php',
  'Yandex\\Fotki\\Exception' => 'source/Yandex/Fotki/Exception.php',
  'Yandex\\Fotki\\Exception\\Api' => 'source/Yandex/Fotki/Exception/Api.php',
  'Yandex\\Fotki\\Exception\\Api\\Album' => 'source/Yandex/Fotki/Exception/Api/Album.php',
  'Yandex\\Fotki\\Exception\\Api\\AlbumsCollection' => 'source/Yandex/Fotki/Exception/Api/AlbumsCollection.php',
  'Yandex\\Fotki\\Exception\\Api\\Auth' => 'source/Yandex/Fotki/Exception/Api/Auth.php',
  'Yandex\\Fotki\\Exception\\Api\\EndOfCollection' => 'source/Yandex/Fotki/Exception/Api/EndOfCollection.php',
  'Yandex\\Fotki\\Exception\\Api\\Photo' => 'source/Yandex/Fotki/Exception/Api/Photo.php',
  'Yandex\\Fotki\\Exception\\Api\\PhotosCollection' => 'source/Yandex/Fotki/Exception/Api/PhotosCollection.php',
  'Yandex\\Fotki\\Exception\\Api\\ServiceDocument' => 'source/Yandex/Fotki/Exception/Api/ServiceDocument.php',
  'Yandex\\Fotki\\Exception\\AuthorizeError' => 'source/Yandex/Fotki/Exception/AuthorizeError.php',
  'Yandex\\Fotki\\Exception\\CurlError' => 'source/Yandex/Fotki/Exception/CurlError.php',
  'Yandex\\Fotki\\Transport' => 'source/Yandex/Fotki/Transport.php',
);
	if ( isset( $map[ $name ] ) )
	{
		require $map[ $name ];
	}
}
spl_autoload_register( '__dm_autoload_325' );
